### ISSUE TITLE
Crash on volume change

### ISSUE THREAD

**Issue by seckela** [Hypnos3/node-red-contrib-cast#10]
If 2 cast nodes clash, the node-red server crashes. Trying to use another short message node at 0 volume as a "stop" command.

**Comment by seckela** [comment]
Error Log:
`ct 04 19:44:01 H0M3 Node-RED[15831]: 4 Oct 19:44:01 - ReferenceError: node is not defined
Oct 04 19:44:01 H0M3 Node-RED[15831]:     at /home/pi/.node-red/node_modules/node-red-contrib-cast/cast-to-client.js:40:17
Oct 04 19:44:01 H0M3 systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Oct 04 19:44:01 H0M3 systemd[1]: nodered.service: Unit entered failed state.
Oct 04 19:44:01 H0M3 systemd[1]: nodered.service: Failed with result 'exit-code'.
Oct 04 19:44:01 H0M3 systemd[1]: nodered.service: Service hold-off time over, scheduling restart.
Oct 04 19:44:01 H0M3 systemd[1]: Stopped Node-RED graphical event wiring tool.`

**Comment by Hypnos3** [comment]
Thank, I will look into this next week.

Mikhail Thomas <notifications@github.com> schrieb am Do., 4. Okt. 2018,
22:44:

**Comment by Hypnos3** [comment]
I have changed several. Can you please check Version 0.0.9?

**Comment by Hypnos3** [comment]
I will close issue. Cou can reopen it if it still exists.
