### ISSUE TITLE
Today the English-GB voice changed to a man

### ISSUE THREAD

**Issue by pcb1962** [Hypnos3/node-red-contrib-cast#102]
Hi, been using this node for about a year, been rock solid and had a pleasant female voice. Today the voice has changed to a man (or maybe it's a 'neutral'). Any idea what can be done to bring back the female voice?
I'm sending only ip, message and volume into the node.
Thanks

Edit: Found a workaround by changing language on the node properties from en to en-AU, but I would have preferred if en-GB could be specified as female. Doesn't look like the google-tts-api node.js library supports this.

**Comment by exemmer** [comment]
Was thinking the same thing myself!

**Comment by melvinraju** [comment]
Have this problem too

**Comment by Hypnos3** [comment]
This seems so be more a problem of google side as the node has no influence which voice google uses.

**Comment by pcb1962** [comment]
Yes that's exactly the case, would need to change the node to use one of the more complex speech APIs to get control over this.

**Comment by melvinraju** [comment]
It has changed back to the normal voice for me. How about you @exemmer @pcb1962 ?

**Comment by exemmer** [comment]
Yup - she's back!

**Comment by pcb1962** [comment]
Yes, back to normal, thanks

**Comment by pcb1962** [comment]
Has remained the same since, hopefully just a slip-up at Google.
