### ISSUE TITLE
google-tts:get key failed from google

### ISSUE THREAD

**Issue by boyphongsakorn** [Hypnos3/node-red-contrib-cast#107]
i set language to thai
and i got this error "Not able to get media file via google-tts:get key failed from google" 
in node-red from home assistant
how to fix that?

**Comment by sheminasalam** [comment]
I am also facing the same issue.

**Comment by Scotison** [comment]
me too. If I continue to hit the node it will go though but only about 50% of the time.

**Comment by Failure404** [comment]
> me too. If I continue to hit the node it will go though but only about 50% of the time.

Same issue here.

**Comment by ayasystems** [comment]
Same issue here also.

I've my own google tts key so where can set it into node-red-contrib-cast??

**Comment by huuub** [comment]
I have the same issue. It works like 50% of the time.

**Comment by fullhack2** [comment]
Same issue here. Seeing inconsistent results.  Some times it works without issue and others it fails with the "Not able to get media file via google-tts:get key failed from google" error.

**Comment by denisjoshua** [comment]
I subscribe... have same problem :-( 
Thanks in advance

**Comment by ktetsuo** [comment]
I have a same problem and I read this.
[zlargon/google-tts#33](https://github.com/zlargon/google-tts/issues/33#issuecomment-723548451)
> The latest version 0.0.5 should work fine.

node-red-contrib-cast is using google-tts-api v0.0.4 now,
so I fixed this problem by following process. (update google-tts-api to v0.0.5)
```:bash
cd ~/.node-red/node_modules/node-red-contrib-cast
npm update google-tts-api
```

**Comment by pcb1962** [comment]
That seems to have fixed it for me, thank you @ktetsuo

**Comment by boyphongsakorn** [comment]
> I have a same problem and I read this.
> [zlargon/google-tts#33](https://github.com/zlargon/google-tts/issues/33#issuecomment-723548451)
> 
> > The latest version 0.0.5 should work fine.
> 
> node-red-contrib-cast is using google-tts-api v0.0.4 now,
> so I fixed this problem by following process. (update google-tts-api to v0.0.5)
> 
> ```
> cd ~/.node-red/node_modules/node-red-contrib-cast
> npm update google-tts-api
> ```

can i use this command to update in home assistant?

**Comment by EtorS** [comment]
> I have a same problem and I read this.
> [zlargon/google-tts#33](https://github.com/zlargon/google-tts/issues/33#issuecomment-723548451)
> 
> > The latest version 0.0.5 should work fine.
> 
> node-red-contrib-cast is using google-tts-api v0.0.4 now,
> so I fixed this problem by following process. (update google-tts-api to v0.0.5)
> 
> ```
> cd ~/.node-red/node_modules/node-red-contrib-cast
> npm update google-tts-api
> ```

Worked!! Thanks! :)

**Comment by huuub** [comment]
Hmm not for me. But I run it from hacs...

**Comment by Hypnos3** [comment]
I have updated the dependencies of google-tts-api to the latest (0.0.5).

**Comment by cw-kid** [comment]
Hi

Can anyone please help me? My Google Home TTS has stopped working. 

I am also now seeing this message in Node Red debug:

"Not able to get media file via google-tts:get token key failed from google"

I ran these commands but its still not working:

`cd ~/.node-red/node_modules/node-red-contrib-cast
npm update google-tts-api`

I seem to have google-tts-api in two different directories:

/home/pi/.node-red/node_modules/google-tts-api

and

/home/pi/.node-red/node_modules/node-red-contrib-cast/node_modules/google-tts-api

Both appear to be version 0.0.5 if I look inside the CHANGELOG.md file. 

Any idea why its still not working or how to fix it ? 

THANK YOU..

**Comment by anhpnh** [comment]
Google continue to lock api ;(((
