### ISSUE TITLE
How to stop streaming

### ISSUE THREAD

**Issue by ChrisSutton123** [Hypnos3/node-red-contrib-cast#108]
[DoorCamera.txt](https://github.com/Hypnos3/node-red-contrib-cast/files/5499325/DoorCamera.txt)

I can successfully stream my door camera to my google nest hub. However I am unable to stop the stream gracefully.
Attached is my node-red flow. What am I doing wrong? Thank you

**Comment by thomasvjohansen** [comment]
I have same problem. want to be able to send at "stop stream" command but how?

**Comment by ChrisSutton123** [comment]
Is this possible?

**Comment by thomasvjohansen** [comment]
I found a workaround to make it stop.

I just play a sec. "of nothing".
A change node with "set msg.duration to 1"

`[{"id":"53d91dd8.67b924","type":"change","z":"cc5bd9e5.26e4a8","name":"stop","rules":[{"t":"set","p":"duration","pt":"msg","to":"1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":280,"wires":[["a21f1807.41d7f8"]]}]`

**Comment by SelfSufficient08** [comment]
Has anyone gotten the msg.duration to successfully send with the original cast?  I set it in the flow and no errors occur but it just runs until it times out in 10 minutes.  My purpose is the front door camera.   I did try thomas's above node but mine still continues to play what was originally played.  No errors.

**Comment by ChrisSutton123** [comment]
workaround doesn't work for me either
