### ISSUE TITLE
TTS timeout

### ISSUE THREAD

**Issue by mifrey00** [Hypnos3/node-red-contrib-cast#110]
I systematically get the following error for some time now "Not able to get media file via google-tts:response timeout at https://translate.google.com over limit: 10000".  It is not a network issue since it works with an URL pointing to a MP3 file.

Node version 0.2.15.

**Comment by magma1447** [comment]
I heard rumors today that Google has added a Captcha to their TTS service. I have not double checked that it's true. But I notice my own TTS nodes have stopped working.

**Comment by Achronite** [comment]
Try this
```
cd ~/.node-red/node_modules/node-red-contrib-cast
npm update google-tts-api
```

**Comment by mifrey00** [comment]
I updated google-tts-api it is now version 0.0.5.  I still have a timeout  _"Not able to get media file via google-tts:Response timeout while trying to fetch https://translate.google.com/ (over 10000ms)"_

**Comment by magma1447** [comment]
> cd ~/.node-red/node_modules/node-red-contrib-cast
> npm update google-tts-api

Solved my issues at least.

**Comment by Hypnos3** [comment]
I have updated the dependencies, so that the node used latest google-tts-api
