### ISSUE TITLE
Suppress Starttone before Audio

### ISSUE THREAD

**Issue by guny74** [Hypnos3/node-red-contrib-cast#112]
Hello,

I do not know if this would be a problem of this node, but playing text or mp3 to my google nest mini , always a starttone appears before the actually audio.

How can iI suppress it ?

Thank you

Regards
  Thorsten

**Comment by Hypnos3** [comment]
Sorry, I havn't found any posibility to Suppress Starttone before Audio.

**Comment by philosoma** [comment]
I have not tried this yet, but let us know if its works: 

https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123/37

**Comment by sergiocntr** [comment]
I don't know if it can help but you can disable the tones before and after the messages from the google home app (
this applies to all messages)

**Comment by guny74** [comment]
Hello,

I also found the idea with the 1-second silence....but an short "plop" always appears.... 
Not nice...but may I get to like this or change to other solution (alexa or lokal MP3 player) for my smart home announcements.

Thanks you.

Regards
