### ISSUE TITLE
german spelling is slower as usual

### ISSUE THREAD

**Issue by helmchen81** [Hypnos3/node-red-contrib-cast#119]
Hi all,

I recently used cast to send out some announcements. I figured out that the spelling speed is about 3/4 as the usual. Checking the google API documentation, it should be possible to send over spelling speed as well as pitch. Is there any possibility to apply this into the node?

Thanks a lot
Sebastian

**Comment by Hypnos3** [comment]
I have updated to the last tts api. Maybe this helps.
