### ISSUE TITLE
Readme not displayed in flows.nodered.org

### ISSUE THREAD

**Issue by Paul-Reed** [Hypnos3/node-red-contrib-cast#15]
Hi Stephen. If you check [your node entry on flows.nodered.org](https://flows.nodered.org/node/node-red-contrib-cast) the readme is missing.
Didn't know if you were aware.

**Comment by Hypnos3** [comment]
Thank you for this information. I will check this today.

Am Di., 30. Okt. 2018, 23:39 hat Paul <notifications@github.com>
geschrieben:

**Comment by Hypnos3** [comment]
I have republished the node at npm and now the readme is visible again.

I do not know what the reason that the readme wasn't displayed.
