### ISSUE TITLE
Unable to get status to work

### ISSUE THREAD

**Issue by i8beef** [Hypnos3/node-red-contrib-cast#16]
I don't seem to be able to get status only to work.

Tried injecting messages with payloads of NULL, {}, "", etc. and they all seem to error out around attempts to fill the data.media object.

I looked over your code, and I think you have several `typeof media === 'object'` where you meant to have `typeof data.media === 'object'`

Also, it seems like the way you do your overloads of the config attributes might be leading to some of those later checks if they were defined earlier always execute? Trying to trace through your code, it seems like I'm getting into sections that I would only expect to get into if things like data.url WERE defined (i.e., not undefined) by nature of you taking the `config[attribute]` first, and these not being undefined, but perhaps either empty strings or null...

Or I'm doing something completely wrong?

**Comment by Hypnos3** [comment]
I think the reason is that the NPM version is behind the Github version. At
the last version I had completely changed to get the status.
In the old way the current playing media every time stopped when try to get
the status.

I need to republish the code to get this working. I will do it as soon as
possible.

Am Mi., 31. Okt. 2018, 06:05 hat Michael Hallock <notifications@github.com>
geschrieben:

**Comment by Hypnos3** [comment]
Please check version 0.1.5. Whith this version this should working.

**Comment by i8beef** [comment]
Well it looks like its still attempting an actual cast though. I.e., if I'm in Netflix when I send a message with a blank string payload, it switches to casting, and returns a status object after that cast?

Are you sure that the `typeof media` on lines 435, 446, and 452 shouldn't be checking data.media of cast-to-client.js? That check would make sense I think in the connectedCallback, but seems wrong in the input handler... but Im not a node developer by trade, so I don't know, just looked off.

Then I think your check against undefined in data.url on line 432 would be why I'm still getting a data.media object, and thus the cast. data.url is NEVER undefined because you default it in cast-to-client.html to "null" which !== undefined. So I think it always falls into that.

**Comment by Hypnos3** [comment]
You are right.

Today I released version 0.1.6 which adresses lot of your findings.

Thank you very mutch.

**Comment by i8beef** [comment]
Seems to get status without trigerring casts and such now, thanks!
