### ISSUE TITLE
Send Youtube or spotify to Chromecast

### ISSUE THREAD

**Issue by soloam** [Hypnos3/node-red-contrib-cast#17]
Hello, is this possible? To send a URL of a youtube movie or Music from spotify to a Chromecast or in te case of the music to the google home?

Thank You for this work

**Comment by ckglobalroaming** [comment]
Post your URL in the MediaURL field.

**Comment by Hypnos3** [comment]
It is simply as ckglobalroaming state only for any URL.

Youtube has changed her protocol, so that this seems currently not to work.

There is a working library:
https://github.com/irfanhabib/youtube-castv2-client

Maybe I find time to implement this later.

**Comment by dalla2** [comment]
Hi,
Also trying to play Spotify by set the URL in MediaURL but I only get "Not able to load media:Load failed Not able to load the media.".

Would really appreciate help with how to play Spotify on node red.

**Comment by Hypnos3** [comment]
hint for me

Example for spotify:
https://gist.github.com/kopiro/5325a559302e78d81739a132ff988652
https://github.com/kopiro/spotify-castv2-client

**Comment by pietrondo** [comment]
And about youtube?
thx

**Comment by Hypnos3** [comment]
Unfortunately, I did not succeed in my tests a long time ago. Currently, I have very little time to deal with Hermit, so that there will be no progress here in the near future.
