### ISSUE TITLE
HomeHub stuck with Chomecast graphic after notification plays

### ISSUE THREAD

**Issue by trouty00** [Hypnos3/node-red-contrib-cast#25]
just started playing with this after i got a homehub and the notification works great but then the screen on the homehub goes black with a simple cast logo in the centre. it goes away after a while but its means to use the device it needs an extra couple of touches. What is the feasibility of adding in a "stop casting" command which would bring it straight back to the home screen.

**Comment by Hypnos3** [comment]
this behaviour is independend of what is playing. I'm searching for a way to resume current playing (see #13). Unfortunately I have not been successful so far .

**Comment by semperor** [comment]
Maybe the [chromecast-java-api-v2](https://github.com/vitalidze/chromecast-java-api-v2) from vitalidze is useful, especially the [Useful links](https://github.com/vitalidze/chromecast-java-api-v2#useful-links).

**Comment by Hypnos3** [comment]
Here is a nodejs implementation. This will need a lot of time for implementation. 
https://github.com/vincentbernat/nodecastor

**Comment by Hypnos3** [comment]
Already implemented stop command. But this needs further testing.
I will follow on this with issue #47

To the useful links, the node is based on
https://github.com/thibauts/node-castv2
https://github.com/thibauts/node-castv2-client

This is already a similar implementation as described in
https://github.com/vitalidze/chromecast-java-api-v2
https://github.com/vitalidze/chromecast-java-api-v2#useful-links

Unfortunately there was no further development in castv2 for 2 years. As as I have noticed Google aims to migration from castv2 protocol to CAF (Cast Application Framework). So it seems to be time t switch to CAF. I still lack an example for nodejs of CAF implementation.

I will close this issue and open another one for migration to CAF. The stop command will be tracked in issue #47
