### ISSUE TITLE
Delay between switching internet radio stations

### ISSUE THREAD

**Issue by Ant422** [Hypnos3/node-red-contrib-cast#26]
Hi,
First time posting here.. Thanks for the node!!
I have started to configure the cast node to play internet radio streams (I'm using chromecast audio). All works wonderfully but there is a gap/delay of about 20 seconds when changing between stations. I seems like it is establishing a new connection each time I change stations as I get the audible 'blonk' .
The flow is simple in that I have buttons with the URLs as the payload going directly to the cast node. I also put in a change node to set the streamType to NONE and LIVE but this didn't seem to reduce the delay.
Would you have any ideas?
Thanks
Ant

**Comment by Ant422** [comment]
A little ore info. The delay only seems to be happening when switching to an m3u stream. When I go to an mp3 stream there is no delay. Any way to resolve this?
Thanks again

**Comment by markusElse** [comment]
I had the same problem and my solution is to simply send a play command once the cast node gave a response:

if(msg.payload.currentTime===0)
{
    return{
      payload: {
        type: "PLAY"
      }
    }
}
