### ISSUE TITLE
cast issue

### ISSUE THREAD

**Issue by patrol420** [Hypnos3/node-red-contrib-cast#27]
hey guys, just started getting this issue when casting TTS has been working fine. 

"Not able to get media file via google-tts:get key failed from google" via debug node on the cast node
any ideas

**Comment by drose28357** [comment]
Version 0.2.1 fixed this issue

**Comment by kiai72** [comment]
hello, i have the same problem. i use version 0.2.4. it says: Not able to get media file via google-tts:get key failed from google

**Comment by Hypnos3** [comment]
Are you sure, that you have installed version 0.2.4?
I have tested it and have no problems.

**Comment by Hypnos3** [comment]
Can you please check that you have installed [google-tts-api](https://www.npmjs.com/package/google-tts-api) version 0.0.4?

**Comment by drose28357** [comment]
I had also a cast client errot. It turned out that the ip adress has changed during DSL router reconfiguration. 
Here is my debug log:
24.1.2019, 09:38:11node: Google Home mini
msg : string[62]
"Client error reported:connect EHOSTUNREACH 192.168.101.28:8009"

**Comment by kiai72** [comment]
> Can you please check that you have installed [google-tts-api](https://www.npmjs.com/package/google-tts-api) version 0.0.4?

yes, i checked. i have cast 0.2.4 and google-tts-api 0.0.4. By the way: i checked to send a audio-file - that works.

**Comment by Hypnos3** [comment]
@kiai72: The node just simply do to convert the textz message by using  google-tts-api to a audio file which is send to the cast device. So thee error "Not able to get media file via google-tts:get key failed from google" comes from google-tts-api. This error should be fixed in google-tts-api with version 0.0.4.

Sorry I can not help here.

**Comment by Hypnos3** [comment]
@drose28357: The Error "Client error reported:connect EHOSTUNREACH 192.168.101.28:8009" states, that the google home mini is not accessible at IP "192.168.101.28" from the Node-Red instance.

 - Is this the right IP Address of your Google Home Mini?
 - Has the new DSL Router any firewall settings that the Device running NodeRed can not access the Google Home mini with this IP?

**Comment by kiai72** [comment]
> @kiai72: The node just simply do to convert the textz message by using google-tts-api to a audio file which is send to the cast device. So thee error "Not able to get media file via google-tts:get key failed from google" comes from google-tts-api. This error should be fixed in google-tts-api with version 0.0.4.
> 
> Sorry I can not help here.

sure! i just wonder, why it works for you. is there any setup for google-tts-api/key that i have to do ?
Bye the way: i know your tool "just sends a audio file" at the moment. Can we enhance it to send a broadcast message instead ?  After a broadcast message - the previous stream continues! that would be helpful for my case.

**Comment by Hypnos3** [comment]
Yes. Can you give me more information how to "send a broadcast message"?

I was not able to find an example.

**Comment by kiai72** [comment]
> Yes. Can you give me more information how to "send a broadcast message"?
> 
> I was not able to find an example.

as far as i know broadcast is only possible between "assistant devices" (2 home, a google assist on android and a home, ...).
there a project that does this: https://github.com/greghesp/assistant-relay
it's standalone, not node-red. but maybe it's interessting for you?

**Comment by Hypnos3** [comment]
Yes this is interesting.

But I think that is a completely different approach. Here you have to get a google API key. That would be something for a new node and nothing for this.

Since I currently lack the time and I'm running too many projects at the same time, I can not say yet if and when I can take a closer look.

**Comment by Hypnos3** [comment]
I collecting that into this issue:
https://github.com/Hypnos3/node-red-contrib-cast/issues/35

**Comment by jkmaxwell** [comment]
Just started happening to me tonight after months of working just fine.

**Comment by lyance** [comment]
Same for me, it's been ok for a few months until the TTS errors start happening a couple of weeks ago.  Casting audio files stored in Google drive is working though.

**Comment by Bash-** [comment]
Same here

**Comment by atkinsonar** [comment]
Seeing the same issue with error "Not able to get media file via google-tts:get token key failed from google"

**Comment by Bash-** [comment]
I updated the cast plugin in NodeRed and it seems to work again
