### ISSUE TITLE
Would it be possible to do pause / play control through this node?

### ISSUE THREAD

**Issue by rgerrans** [Hypnos3/node-red-contrib-cast#28]
I'm looking for the ability to control my Chromecast in order to pause / play it. I can do so using Google Assistant voice commands so assume there should be someway to inject those commands as well?

Thanks for all the great work on this.

**Comment by Hypnos3** [comment]
You can try to set message property `msg.pause` or `msg.resume`. That should given directly to the chromecast. I have this implemented, but not testet yet. A resume is not available.

**Comment by rgerrans** [comment]
I upgraded to the latest build.  I'm assuming to just set them to true but they don't seem to be having any control on the device? Any info I can pull to help troubleshoot?

**Comment by herzogmedia** [comment]
Hello there, 
I've tried `msg.pause` as well and had no effect. What kind of payload should that have? boolean `true`? Does that even matter? Thanks for your help!

**Comment by Hypnos3** [comment]
For `resume` no support through the castv2 protocol are given. `stop` and `pause` may be supported, but this needs further testing. Close thia issue and follow on with issue #47.
