### ISSUE TITLE
Can't mute google home 

### ISSUE THREAD

**Issue by pepedros** [Hypnos3/node-red-contrib-cast#29]
Hi, I have a problem to mute my google home mini.

Volume parameter can't be 0, it only works between 1 and 100. Muted parameter also doesn't work. How to mute my device?

**Comment by Hypnos3** [comment]
Please, can you check if it will working with Version 0.2.2?
Maybe check to set message property `msg.muted` to `true`.

**Comment by pepedros** [comment]
Thanks for reply, I'll check it in next week. I don't have access to my home mini right now.

**Comment by pepedros** [comment]
@Hypnos3 
I just made some debug:
`msg.volume = 0;` set in script option.volume to undefined (rest are correctly set as number value)
`msg.muted = false;` set in script  option.muted to undefined (true is correctly set as true)

**Comment by pepedros** [comment]
unmited still not working.
`msg.volume = 0` not working, but when i set volume to 0 in node properties it works. Also, when i set `msg.volume = 0.01` it also set volume to 0%.

I change in my code to:
`if (typeof options.muted !== 'undefined' && options.muted != null) {
            doSetVolume({
                muted: **(options.muted === "on")**
            });
        } 
`
and I can shwitch muted state with "on"/"off" value. - this works perfectly

also change below code and value "0.01" only change volume level without muting.
`if (typeof volume === 'object') {
            obj = volume;
        } else {
            **if (volume < 0) {
                obj = {
                    level: volume
                };**
            } else if (volume > 0.99) {
                obj = {
                    level: 1
                };
            } else {
                obj = {
                    level: volume
                };
            }
        }
`

**Comment by Hypnos3** [comment]
I was able to test and reproduce the error. It is fixed in Version 0.2.4.
