### ISSUE TITLE
Allow Hostname to used instead of IP

### ISSUE THREAD

**Issue by cbulock** [Hypnos3/node-red-contrib-cast#30]
The IP field already does allow hostnames to be entered, and it works fine, however, there is some input validation being done and the nodes complain that they aren't configured correctly if a hostname is entered.

As I have a large number of cast capable devices, I much prefer to use hostnames to keep track of them. So it would be nice if hostnames could be supported.

**Comment by Hypnos3** [comment]
I must check if the underlying library can handle Hostname.

**Comment by Hypnos3** [comment]
I have changed the input validation in version 0.2.3. I'm currently not able to test. Can you please test it?

**Comment by cbulock** [comment]
Works perfect with version 0.2.3, thank you!
