### ISSUE TITLE
MJPG Support

### ISSUE THREAD

**Issue by slombard3000** [Hypnos3/node-red-contrib-cast#31]
I have a camera that sends Mjpgs as many do (Motion software). I can't seem to figure out if this will work with Cast. I'm looking to stream this camera if motion is detected.

Any ideas?

**Comment by soloam** [comment]
I would like to do that also! I can cast my camera to the chromecast if I use the android app tinycam pro! It would be nice to have the same behavior in node red!

**Comment by Hypnos3** [comment]
I don't know, but I think this needs some conversation of the file format.

**Comment by Hypnos3** [comment]
Unfortunately I have no device which delivers Mjpgs. So I can not test that. However, if someone has a solution, I like to accept a PR.
