### ISSUE TITLE
Security Vulnerbility

### ISSUE THREAD

**Issue by rgerrans** [Hypnos3/node-red-contrib-cast#32]
Just got this on doing some maintenance to my system:

![image](https://user-images.githubusercontent.com/18623772/50674495-1f8e8d80-0fa4-11e9-8fd8-89a706317bc5.png)

**Comment by Hypnos3** [comment]
The Problem occurs in an underlying library. I have opend an issue there.

**Comment by Hypnos3** [comment]
I will close this, because I still waiting of fix this in the usted lib.
