### ISSUE TITLE
node.error causing Nodered to crash

### ISSUE THREAD

**Issue by aaamoeder** [Hypnos3/node-red-contrib-cast#350]
This is the same issue as #337 but has not been fixed.

Somehow this causes NR to crash.
For the time being I commented out the affected lines of code but it's a less than ideal solution.

Hopefully it can be fixed.
Thanks in advance !

**Comment by antz-d** [comment]
having same issue, tried node-red-contrib-castv2 but not having much luck.
any attention to this issue would be appreciated
