### ISSUE TITLE
remove announcement tone (bing) when play mp3/tts

### ISSUE THREAD

**Issue by ozett** [Hypnos3/node-red-contrib-cast#39]
i fi cast a mp3 file to a google-home-mini, before it is played a here an announcment tone.
if i cast tts to the same device, this is not the case.

is this configurable for mp3 or the google-cast default if a mp3/sound is played?
( rather dont want this announcment-beeping-tone)

my test-flow in node-red:

```
[{"id":"201e8c6c.2f5a44","type":"inject","z":"427e39a5.89c7f8","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1262,"y":164,"wires":[["80067ba4.cd8308"]]},{"id":"80067ba4.cd8308","type":"change","z":"427e39a5.89c7f8","name":"settings","rules":[{"t":"set","p":"ip","pt":"msg","to":"192.168.14.40","tot":"str"},{"t":"set","p":"language","pt":"msg","to":"de-DE","tot":"str"},{"t":"set","p":"volume","pt":"msg","to":"80","tot":"str"},{"t":"set","p":"url","pt":"msg","to":"http://192.168.14.30/motion/1/snd/44149__stickinthemud__chimes-2sec-gliss-down.wav","tot":"str"},{"t":"set","p":"contentType","pt":"msg","to":"audio/mp3","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1435,"y":208,"wires":[["31a7b97.e381e46","b758720.7a4439"]]},{"id":"b758720.7a4439","type":"cast-to-client","z":"427e39a5.89c7f8","name":"","url":"","contentType":"","message":"","language":"","ip":"","port":"","volume":"","x":1648,"y":207,"wires":[["73a911f2.41a8d"]]}]
```

thanks for info,
toz

**Comment by Hypnos3** [comment]
I have not found a way to control the announcment tone.

What do you mean with:
if i cast tts to the same device, this is not the case.

The node-red-contrib-cast tts creates a mp3 which is send to the cast device. So in my case I get also the announcment tone for playing any tts mp3.

**Comment by ozett** [comment]
yes, you are right, the annoucement-tone is also played with TTS spoken text.
my mp3 was a music file, so i heard first the annoucement tone, than music playing.
this was a little weired. 

as there is spoken text, the annoucement-tone seemed more natural to me, so i did not really recognized this annoucement as prepended "tone". 

but you are right.

it keep this thread "watched" if anybody finds a way to control the annoucement-tone.

thankx,
toz

**Comment by ratsputin** [comment]
This is a function of the Chromecast firmware.  With the most recent update, you can turn this off in the Google Home app under the settings for the device.  This is under Video Settings>Playback sounds>Cast start and volume changes.

**Comment by ozett** [comment]
i have version 2.14.50.10 and dont see video-setting and the volume-setting,
do i have to update?

**Comment by ratsputin** [comment]
My Chromecast Audio is running firmware version 1.42.172094.  This is the most recent release version (see [here ](https://support.google.com/chromecast/answer/7124014?hl=en) for the version list).

My app (iPhone) is version 2.14.510.

**Comment by Paul-Reed** [comment]
I think that the facility to mute the announcement tone only applies to casting to Chromecast and not your home mini.
