### ISSUE TITLE
Error to: say a text

### ISSUE THREAD

**Issue by nrsf** [Hypnos3/node-red-contrib-cast#40]
Hi there!

I am getting the following error :

**21/02/2019 16:10:34node: e04f7d00.1b56b
msg : string[74]
"No contentType given!, using "audio/basic" which is maybe wrong! (Word Up)"
21/02/2019 16:10:36node: e04f7d00.1b56b
msg : string[62]
"Not able to load media:Load failed Not able to load the media."**

When try to SAY TEXT using the demo:

`[{"id":"e04f7d00.1b56b","type":"cast-to-client","z":"4331a068.20dce","name":"","url":"","contentType":"","message":"","language":"en","ip":"","port":"","volume":"","x":450,"y":340,"wires":[["af79d587.e4d278"]]},{"id":"816a96d2.2c7458","type":"inject","z":"4331a068.20dce","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":340,"wires":[["edd9531a.0b39b"]]},{"id":"edd9531a.0b39b","type":"change","z":"4331a068.20dce","name":"","rules":[{"t":"set","p":"ip","pt":"msg","to":"192.168.1.101","tot":"str"},{"t":"set","p":"url","pt":"msg","to":"Word Up","tot":"str"},{"t":"set","p":"language","pt":"msg","to":"En-gb","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":260,"y":340,"wires":[["e04f7d00.1b56b"]]},{"id":"af79d587.e4d278","type":"debug","z":"4331a068.20dce","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":630,"y":340,"wires":[]},{"id":"80194b85.f3bf78","type":"comment","z":"4331a068.20dce","name":"say a text","info":"","x":140,"y":300,"wires":[]}]`

**Comment by nrsf** [comment]
It is now working using:

`[{"id":"e04f7d00.1b56b","type":"cast-to-client","z":"4331a068.20dce","name":"","url":"","contentType":"","message":"","language":"en","ip":"","port":"","volume":"33","x":450,"y":340,"wires":[["af79d587.e4d278"]]},{"id":"816a96d2.2c7458","type":"inject","z":"4331a068.20dce","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":340,"wires":[["edd9531a.0b39b"]]},{"id":"edd9531a.0b39b","type":"change","z":"4331a068.20dce","name":"","rules":[{"t":"set","p":"ip","pt":"msg","to":"192.168.1.101","tot":"str"},{"t":"set","p":"message","pt":"msg","to":"Olá Nelson","tot":"str"},{"t":"set","p":"language","pt":"msg","to":"Pt-br","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":260,"y":340,"wires":[["e04f7d00.1b56b"]]},{"id":"af79d587.e4d278","type":"debug","z":"4331a068.20dce","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":630,"y":340,"wires":[]},{"id":"80194b85.f3bf78","type":"comment","z":"4331a068.20dce","name":"say a text","info":"","x":140,"y":300,"wires":[]}]`

**Comment by nrsf** [comment]
To solve the problem I had to change the demo code from:
`{"t":"set","p":"url","pt":"msg","to":"Word Up","tot":"str"},`
to:
`{"t":"set","p":"message","pt":"msg","to":"Word Up","tot":"str"},`

**Comment by Hypnos3** [comment]
Thank you, I will fix the demo

**Comment by Hypnos3** [comment]
fix will be in the next release
