### ISSUE TITLE
Version 0.2.5 Port issue

### ISSUE THREAD

**Issue by AndrewBarfield** [Hypnos3/node-red-contrib-cast#43]
Specifying a Port number in node properties causes a flow to fail and Node Red's front end to disconnect from the server temporarily. (As a consequence this prohibits group casting.)

Steps to Reproduce:

1) Use any flow containing a Cast node.
2) Specify a Port number either manually or by selecting a device from the list.
3) Deploy and execute the flow.

Results:

![Screenshot from 2019-03-14 13-07-51](https://user-images.githubusercontent.com/1271409/54376900-6ced4200-465a-11e9-90ea-dc1a2ff11a9d.png)

**Comment by Hypnos3** [comment]
fixed with 0.2.6
