### ISSUE TITLE
How to change the default streamType

### ISSUE THREAD

**Issue by Ant422** [Hypnos3/node-red-contrib-cast#44]
Hi,
Could you please let me know how I can change the streamType? I have tried using a change node and set the msg.streamtype to LIVE but it doesn't seem to change when looking at the debug output.
I have also tried to find where the default setting is.  I'm not a coder so this is difficult for me. I have search through 'cast-to-client.js' and found 3 locations where there is 'BUFFERED' mentioned. I changed these to LIVE but no luck.

Any ideas? I'm still trying to find a way to reduce the gap when switching between radio streams.

Thanks

**Comment by Hypnos3** [comment]
Sorry for the late response.
You must set `msg.streamType` to `LIVE` with a change node (Please note upper and lower case - the T must be upper case).

But I have to admit that I did not really test it myself.

**Comment by Hypnos3** [comment]
docu will be enhanced in next releade
