### ISSUE TITLE
Not able to load media:Load failed Not able to load the media.

### ISSUE THREAD

**Issue by owarek** [Hypnos3/node-red-contrib-cast#46]
What: `Not able to load media:Load failed Not able to load the media.` with no sound from Google home mini
When: I am senfing this message to node:
```{"topic":"notification/broadcast/speaker/normal/url","payload":"","qos":1,"retain":false,"_topic":"notification/broadcast/speaker/normal/url","_msgid":"7da166e5.bf4668","url":"http://soundbible.com/grab.php?id=2185&type=mp3","contentType":"audio/mp3"}```

It was working like this for 4 months until today. Do you know what could be the problem?

**Comment by Hypnos3** [comment]
I have no idea. Need more check.

**Comment by eliluong** [comment]
I have same problem now, too. Unable to cast any local file or stream to any device (mini, home hub). I've rebooted devices, rebooted node-red, verified local audio file is playable. Able to cast music from phone app to the device, though.

**Comment by Hypnos3** [comment]
still needs check
