### ISSUE TITLE
Set-up "ContentTitle"

### ISSUE THREAD

**Issue by jvondrus** [Hypnos3/node-red-contrib-cast#49]
Hello,
would be nice to have some way how to set "ContentTitle" manually. Generating "ContentTitle" from text-to-speach message url is not so nice.
Add this settings please or make connect "msg.topic" to "ContentTitle".

Thank you.

**Comment by Hypnos3** [comment]
Will included in the next release

**Comment by jvondrus** [comment]
Great, thank you.
