### ISSUE TITLE
Image content

### ISSUE THREAD

**Issue by balintandras86** [Hypnos3/node-red-contrib-cast#50]
Could images (jpg or png) be casted to Chromecast? Video and audio contents work well, but i have trouble with images. If they can't, is there any solution to cast them with nodered?

**Comment by Hypnos3** [comment]
Have you try to send a link to a picture?

**Comment by balintandras86** [comment]
Yes, of course, but I get error message ("not able to load media"). Url to image file is working in the browser, so it's not misspelled. I tried to set content type, but nothing worked.

**Comment by korniza** [comment]
I get also the same issue. does it required any specific size?

**Comment by korniza** [comment]
some basic troubleshooting: when sending mp3 audio, image appeared. When is just tts, the image appeared to be node-red icon.

**Comment by Hypnos3** [comment]
still open
