### ISSUE TITLE
Not able to load video

### ISSUE THREAD

**Issue by mikerenna** [Hypnos3/node-red-contrib-cast#54]
Haven't found any other post with a fix. Trying to troubleshoot casting of video. I can cast a static image url from my blue iris servers to a google home hub but when trying a video url it fails. hub  reacts by showing a cast icon, then for a few seconds shows a media control (play button and line, which is the same as when I succesfully cast this feed using home assistant), but then it gets another cast icon, and does nothing else. Node-red shows "error load media" under node and this debug message: "Not able to load media:Load failed Not able to load the media." Config is straightforward: 
![image](https://user-images.githubusercontent.com/44856262/57798948-976b8200-7713-11e9-854e-27f0f7329a36.png)

I've tried various video content type and Blue Iris urls, such as one for H264. Also tried urls direct to the cameras, bypassing blue iris. 

Anyone have any ideas on troubleshooting? Would love to use this to dynamically cast live feed instead of static image. 

Thanks in advance!

**Comment by Hypnos3** [comment]
That you can send pictures is more than I expected. ;)

Since I does not own a home hub, I can't test this.

**Comment by mikerenna** [comment]
Fair point. i hadn't tried it against any of my traditional tv/chromecasts, but I had assumed hub would work the same. in just about every case i've tried casting to hub worked just like casting to my tvs.

**Comment by Hypnos3** [comment]
There is a limitation of [supported media types and codecs.(https://developers.google.com/cast/docs/media).

Is your video one of the described formats?
