### ISSUE TITLE
Web page casting

### ISSUE THREAD

**Issue by LeeJoeIng** [Hypnos3/node-red-contrib-cast#55]
Hi, I would like to know is it possible to cast a web page simply by giving the url of the website ? 
If yes, which media type should i enter ? Thanks!

**Comment by Hypnos3** [comment]
[The documentation from Google say](https://developers.google.com/cast/docs/media):
All Google Cast receiver applications support the following.

Image formats

- BMP
- GIF
- JPEG
- PNG
- WEBP

Media container formats

- AAC
- MP3
- MP4
- WAV
- WebM

So WebPages are not supported from Google side.
