### ISSUE TITLE
connection error when triggered using anything other than demo code

### ISSUE THREAD

**Issue by somni-a** [Hypnos3/node-red-contrib-cast#56]
Hypnos3,
I am seeing the exact same issue as this person (who has not resolved their problem, as far as I know)   [https://discourse.nodered.org/t/flow-works-in-one-lineup-but-not-in-others/11018](url) 
In a nutshell, I have my Google Home unit making announcements, triggered via timestamp inject.  But when I try to use any other means of triggering, it breaks with this error:
`Client error reported:connect ECONNREFUSED 192.168.1.106:68`
Note that the port is wrong...I haven't changed the default from 8009.
However, I am using UDP port 67 to detect a MAC address and trigger an announcement; but debug doesn't show anything unusual.  Any insight?

**Comment by Hypnos3** [comment]
The reason is very easy. The UDP node sets msg.port which will also use the cast node. Please add a change node in front of the cast node, which deletes msg.port and it should work.

**Comment by somni-a** [comment]
Hypnos3,
Thanks much....this indeed fixed my issue.  My apologies for taking so long to respond; I just moved house and we are now finally settled in.
