### ISSUE TITLE
choose voice used for tts

### ISSUE THREAD

**Issue by phirestalker** [Hypnos3/node-red-contrib-cast#57]
Is it possible to add the option to choose what voice is used to generate the speech through the google tts? I know Google now offers some choices on assistant for en-us users, but I don't know if they allow you to choose through the tts API. If they do I would like to choose the voice in the node.

**Comment by Hypnos3** [comment]
Can you please check if it will work if you choose as [language](https://cloud.google.com/text-to-speech/docs/voices) some like "en-US-Wavenet-A"?

There will be a validation error, but this should not matter.

**Comment by phirestalker** [comment]
no go. It says "Not able to load media:Load failed Not able to load the media."

**Comment by Hypnos3** [comment]
Ok, this is an other problem.

Voices currently not supported by the underlying [api](https://github.com/zlargon/google-tts).

**Comment by sheminasalam** [comment]
Has the voice selection function been incorporated to this node?

**Comment by Hypnos3** [comment]
No, the node uses the Google translate api and this does not support other voices.
