### ISSUE TITLE
status returns nothing

### ISSUE THREAD

**Issue by marc-gist** [Hypnos3/node-red-contrib-cast#62]
I am trying to get the status.  Tried the sample from the readme, works fine, if I've sent a command recently to the device.  If I have not used the device for some time, and I try to get the status (i.e. i want current volume level), nothing is returned.

Payload just has this:

`{"applications":[]}`

Where if I have it cast a TTS, then ask for status via example code I get the expected data in payload.

**Comment by cougarek** [comment]
Same here. For me problem exists only when polling Home Mini device. Chromecast device returns a valid status.

**Comment by marc-gist** [comment]
@cougarek  interesting... i get empty on any Google Home device (Mini, standard and Max), have yet to try on my Chromecast device.

**Comment by cougarek** [comment]
I just would like to report that the issue is still present. Now it propagated to Chromecast Audio devices. Surely its a firmware update from Google.

**Comment by Hypnos3** [comment]
needs still investigation
