### ISSUE TITLE
Status when file is actually playing?

### ISSUE THREAD

**Issue by slurpey** [Hypnos3/node-red-contrib-cast#64]
Is there a way to get a status when the stream is actually playing vs waiting for connection?

Context:
- old radio - 5 buttons, each one to a stream
- Sometimes, it takes 1 min before audio starts after change of station
- I checked the object while google is in "waiting to load" and after it's playing and they are identical.

I was hoping to get a status "waiting to play" or something so I could trigger some loading lights or something. Thanks (and thanks a lot for this in all cases!!!)

**Comment by Hypnos3** [comment]
The used cast protocol is very limited and marked as obsolete by Google.

In addition, there seems to be only limited development in the library which is used by this node.
