### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by fmartingr** [Hypnos3/node-red-contrib-cast#65]
Trying to search for devices  fail because a request to  `/ipaddresses` is made and that returns 404.

I've  searched  for `ipaddresses`  in the code and that route does not seem to be defined, did I miss some configuration?

**Comment by mrdarrengriffin** [comment]
Same here

**Comment by Hypnos3** [comment]
I can't reproduce this. Ar me the Button is working
![image](https://user-images.githubusercontent.com/12692680/65550419-d1e5f680-df1f-11e9-92b5-ba92f7fea98c.png)

**Comment by fmartingr** [comment]
My node-red version is 0.20.7 and cast plugin 0.2.9 (under ARM7). Still the same problem. I will try tomorrow updating to 0.20.8 in case is any of the fixes of that release.

Do you have any flow that provides the `/ipaddresses` route?

**Comment by Hypnos3** [comment]
My tests are done under the latest beta of Node-RED 1.0. 

The `ipadresses` is a node red Admin entry point which is registered in cast-to-client.js line 912

**Comment by fmartingr** [comment]
I just tried on 1.0.0-beta4 with same results. :(

**Comment by mrdarrengriffin** [comment]
Yeah same here, can't seem to pinpoint the issue.
![ipaddresses](https://user-images.githubusercontent.com/6920899/65624422-c5b27580-dfc1-11e9-885f-4f64ee4c75ef.PNG)

**Comment by mrdarrengriffin** [comment]
I have solved my issue by making sure I place in the node, DEPLOY it without any configuration, and then search.

The reason for this is that the discoverIpAddresses() function isn't called until it is deployed into the flow.

Please try and deploy first and search.

**Comment by fmartingr** [comment]
Using the "trick" from @mrdarrengriffin works, but I had to do a full deploy (I commonly use the "Modified flows" option only) for it to work. Maybe this is some kind of limitation from node red?

**Comment by mrdarrengriffin** [comment]
@fmartingr I never use that feature. Must be a full deploy that fixes it then

**Comment by Hypnos3** [comment]
Yes, it could be a limitation that admin points in node-red only registered if a node is deployed. I will check if I can enhance the error message for that case.

**Comment by amenk** [comment]
In my case the problem appeared because I was running node-red in a docker container in bridge mode. When running it in host mode, mDNS started to work.
