### ISSUE TITLE
No sound on Smart Display - Lenovo 8

### ISSUE THREAD

**Issue by rjmcfadd** [Hypnos3/node-red-contrib-cast#66]
I'm using this node for TTS announcements with home assistant. It works great for my Google Home and Home mini but it doesn't work with my Lenovo smart display. I only get the connection sound but the TTS doesn't play.

**Comment by Hypnos3** [comment]
Unfortunately I have a Lenovo smart display, unfortunately I can not investigate that.

**Comment by gsbrown** [comment]
I am having the same issue; the connection chime happens and the either the message will not play or it will get cut off almost immediately. Only seems to happen with the lenovo smart display.

**Comment by paddy0407** [comment]
May be a point to note, but when an SSL cert isn't set up on Home Assistant, a standard Google Home speaker will have the same symtom. Just in case the Lenovo has an alternative method for SSL encryption or something...

**Comment by paddy0407** [comment]
Does TTS work within HomeAssistant with tts.google_say to the lenovo smart display?
