### ISSUE TITLE
Node-RED 1.0 error logged

### ISSUE THREAD

**Issue by ratsputin** [Hypnos3/node-red-contrib-cast#69]
When casting MP3 content coming back from Amazon Polly (natural text-to-speech service) under Node-RED 1.0, I'm seeing the following errors logged in my syslog:

```
Oct 11 08:26:39 hass Node-RED: 11 Oct 08:26:39 - [info] [cast-to-client:Play message] volume changed to 100
Oct 11 08:26:40 hass Node-RED: (node:86273) UnhandledPromiseRejectionWarning: TypeError: node.error is not a function
Oct 11 08:26:40 hass Node-RED: at errorHandler (/srv/homeassistant/.node-red/node_modules/node-red-contrib-cast/cast-to-client.js:53:14)
Oct 11 08:26:40 hass Node-RED: at googletts.then.catch.err (/srv/homeassistant/.node-red/node_modules/node-red-contrib-cast/cast-to-client.js:196:9)
Oct 11 08:26:40 hass Node-RED: at processTicksAndRejections (internal/process/task_queues.js:86:5)
Oct 11 08:26:40 hass Node-RED: (node:86273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```
This appears to be content-specific, as other mp3 files play just fine.  I should note that playing the mp3 file back on my browser or casting it to my Chromecast Audio via Home Assistant services works fine as well.

The odd part of this is that the error is being thrown from ``cast-to-client:Play message``; however, this isn't a TTS call.  A call from another flow gives this message:

```
Oct 11 08:30:19 hass Node-RED: 11 Oct 08:30:19 - [info] [cast-to-client:d91f85cd.1b1738] volume changed to 25
```
I'm suspicious there may be an issue with one of the messages that are being passed to the node and will pursue this from that end; however, I thought the ``node.error is not a function`` message would interest you.  I don't know if this is new behavior under Node-RED v1.0 or not.

**Comment by ratsputin** [comment]
Okay, the issue was some spurious data in ``msg.payload``.  Deleting it cleared up the error and playback returns now.  There is, however, still the issue with ``node.error`` not actually flagging an error when one occurs and instead crashing under this version of Node-RED.

**Comment by Hypnos3** [comment]
Thank you, I will investigate

**Comment by ratsputin** [comment]
Just another piece of information related to this issue.

I was having issues with my WiFi and my ChromeCast Audio's connection apparently reset while this module was playing an mp3.  I saw this in my logs (as expected):

```
Oct 28 00:22:10 hass Node-RED: 28 Oct 00:22:10 - [error] [cast-to-client:Play message] Client error reported:read ECONNRESET
Oct 28 00:22:10 hass Node-RED: 28 Oct 00:22:10 - [info] [cast-to-client:Play message] { Error: read ECONNRESET
Oct 28 00:22:10 hass Node-RED: at TLSWrap.onStreamRead (internal/stream_base_commons.js:171:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```
Unfortunately, this resulted in the node being stuck in a "client error" state and being unable to play anything back until Node-RED is restarted.  The node shows a "red dot" with "client error" next to it.

I just wanted to pass along some further information on the error.  It appears that any fatal error during playback will render the node "dead" until Node-RED is restarted.  Furthermore, I do have another, separate and unrelated flow that uses this code as well.  It is continuing to play just fine (it was not impacted by the "hit"), so this is a per-instance issue.

Kind regards.
