### ISSUE TITLE
RSTP Stream

### ISSUE THREAD

**Issue by paddy0407** [Hypnos3/node-red-contrib-cast#72]
Is it possible to cast with RSTP stream? I'm using defang hacks but am having issues with docker HA and the stream component with .m3u8 from the camera.
If it were possible to grab the stream from rtsp://192.168.x.xxx:8554/unicast, the whole process would be easier.

I could be missing something staring me in the face....

**Comment by Hypnos3** [comment]
I have no idea.

**Comment by realjax** [comment]
As fas as I know it is not possible to stream RTSP directly to a cast device.  You might be able to get Node Red to do this by using something like [NORA](https://github.com/andrei-tatar/node-red-contrib-nora). But that would mean an additional 'camera' component needs to be developed first *and* you need a stream format which is one of the [these](https://developers.google.com/assistant/smarthome/traits/camerastream#video-formats).

**Comment by madmaiike** [comment]
They mentioned using motioneye (https://github.com/ccrisan/motioneye/wiki) stream URL and media type as JPG - don't have a video camera at hand to test it out unfortunately. Would love to automate and display who's at the door when bell rings or send to phone.
