### ISSUE TITLE
How to catch exception thrown by Cast node on overlapping messages?

### ISSUE THREAD

**Issue by pcb1962** [Hypnos3/node-red-contrib-cast#73]
Cast node is working great for me, thank you, but I have one issue that I'd like to tidy up. 
If I trigger a new message before the current message output has completed I get an error message in the debug sidebar, with red borders, saying:

11/24/2019, 11:53:27 PMnode: Cast
msg : string[101]
"Not able to load media:Load cancelled The request was cancelled (a second load request was received)."

I get one of these messages for each device I'm casting to, so if I'm doing a broadcast I get a whole load of these messages.
I've tried catching this with a Node-RED catch node, but that doesn't work. Is there any way to suppress this message from appearing in the debug sidebar?

**Comment by pcb1962** [comment]
Solved this, see the comment by Nick here: https://stackoverflow.com/questions/49453283/node-red-catching-error-node-red-contrib-composer
Tried to create a pull request but it wanted to commit 139 changes into stephenkeep/node-red-contrib-chromecast
To fix the issue, in the file cast-to-client.js change the line 
 node.error(messageText);
to
 node.error(messageText,{topic:"Cast_error",payload:messageText});
or similar

**Comment by Hypnos3** [comment]
Ok, I will merge this tomorrow.

**Comment by GiacomoTorrigiani** [comment]
![HA](https://user-images.githubusercontent.com/101568206/196805663-80d2132a-546a-451d-b2f1-942c9badad21.PNG)
![Cattura](https://user-images.githubusercontent.com/101568206/196805790-ae42d6ff-e565-4505-bdb9-85f39d76f5cd.PNG)
i can't find the folder nor the javascript file, i'm using home assistant

**Comment by GiacomoTorrigiani** [comment]
can you help me? @pcb1962
