### ISSUE TITLE
Casting icon still displayed after casting a mp3

### ISSUE THREAD

**Issue by djmvt** [Hypnos3/node-red-contrib-cast#78]
Completely new to node-red so sorry if this is a dumb question:

I've managed to make a flow that sends an mp3 to my google home groups but noticed that, when the file is done playing, the cast icon is still visible on the nest hub.
Also in google home the other devices still have the "stop casting button" so it is still connected to the casting from node-red. Any way to fix this?

thanks!
Learning every day.

**Comment by realjax** [comment]
I have the same problem.

**Comment by Anjerlaan** [comment]
Me too....thought that **msg.duration** would do the trick, but I can't get it to work either.
Does anyone got **msg.duration** to work?

**Comment by djmvt** [comment]
I've stopped using this node.

**Comment by Anjerlaan** [comment]
> I've stopped using this node.

Why, if i may ask?

**Comment by djmvt** [comment]
Because someone made a plugin for pimatic (the domotica software i'm using) that does what this node does and is integrated in the domotica software.

**Comment by Anjerlaan** [comment]
Ah ok, but isn't this plugin using the same api?

**Comment by djmvt** [comment]
Probably. But it's of no use for me to use a different (node-red) platform when I've got everything connected in pimatic.
