### ISSUE TITLE
Is it yet possible to stream an mp3 from a public googledrive shared url?

### ISSUE THREAD

**Issue by JacHub** [Hypnos3/node-red-contrib-cast#79]
I want to play mp3 files on my google home after certain events. But it is difficult to play local files. I put an mp3 on my google drive and created an share. Now i want to play this file but i think this in not possible?

**Comment by willquah** [comment]
actually, i managed to get exactly what you’re describing working really well, you just have to make a public directory to host the files, and then feed the node the url of the file location. i used the windows iis to make a public directory in inetpubs wwwroot on my local machine, and with a static assigned local ipv4 (same subnet) address the google homes had no issues playing the audio despite not having https or any sort of security certification at all. and this works even if the files are hosted on a different machine to node-red. 
i think getting your stuff up and down from the cloud is what is giving you trouble, along with the security layers involved in checking in and out each device that’s accessing the cloud drive. just tinker with local file shares and you should manage it eventually.
