### ISSUE TITLE
Volume Issue on Google Home Mini v2

### ISSUE THREAD

**Issue by Anjerlaan** [Hypnos3/node-red-contrib-cast#81]
Hi,

I am playing around with your google cast nodes. Nice work!
When I cast a local audio clip (doorbell.mp3) to my Google Home Mini (v2) I notice a strange thing.
If the **msg.volume** is louder then 45 then a strange sound is played, along with the local Mp3 sound. Normally the Mini first plays a confirmation sound (click) and then the Mp3, Stream or Message is played, but if the volume is louder>45, then this click sound is a strange sound on top of the Mp3.

Any idea what this can be?

**Comment by Hypnos3** [comment]
Sorry , I have no idea.

**Comment by Anjerlaan** [comment]
OK, i have an other issue, how can the cast be stopped/removed.....when a short audio/MP3 file is finished, the cast icon is still shown on the mini, until i delete it on the mini
