### ISSUE TITLE
Not sure it's returning the object

### ISSUE THREAD

**Issue by jkmaxwell** [Hypnos3/node-red-contrib-cast#86]
Hi, I used your sample code to return the Cast object to see if I could retrieve the volume. As far as I can tell, it's only returning a partial object.

In this sequence I first try the object, then what I believe the syntax would be for the volume level, then the application object just to poke around, but it appears empty.

![image](https://user-images.githubusercontent.com/342903/76734160-8dddec80-671f-11ea-8dda-ccf7bf6ac031.png)

PLMK if I am doing this wrong or if it is not behaving as expected. If the former, what should I be doing differently? I assumed that by using your example I would receive the same object, but I did not.

**Comment by syrisara** [comment]
Yep,

I'm having the same issues, sometimes however it works but I can not reproduce this.

**Comment by bjschuit** [comment]
I've got the same problem. I'm casting messages to the Google cast devices and I'd like to restore their operation (like volume, stream, etc.) when the message has played. However, the object it returns is empty. When I 'wake' the devices with sending a message, the array is filled, also next time I poll their status. But it seems there is some sleep functionality after which the devices return no status.

**Comment by EdB1972** [comment]
Is it possible to resume audio / video playback via the castable devices when playing a tts?

Example: Listen to TuneIn on Google Home and a regularly scheduled TTS message appears. It will stop the stream, play the tts message. Resume TuneIn stream.

if possible someone can help me to export a sample from node red.

**Comment by chrisella** [comment]
I'm also experiencing this, much as bjschuit described.
