### ISSUE TITLE
How to cast a youtube video using video url?

### ISSUE THREAD

**Issue by ahakobyan79** [Hypnos3/node-red-contrib-cast#87]
I can't seem to make a youtube URL video to steam to chromecast.

Please help.
Thanks.

**Comment by Hypnos3** [comment]
Unfortunately, I have not yet succeeded in doing so.

**Comment by madmaiike** [comment]
Same here, was excited about it :) I get the following error message : 

Not able to load media:Load failed Not able to load the media.

Did I miss something in the documentation ?

**Comment by guyluz11** [comment]
Let's keep this issue open in case someone wants to work on it.

I think it is a highly requested feature so one open issue for that will be better than opening and closing each one automatically by a stale bot. 
Is there a label that overrides the bot intervention?

**Comment by paloss** [comment]
So, did someone ever figured this out?

**Comment by guyluz11** [comment]
[node-red-contrib-castv2](https://flows.nodered.org/node/node-red-contrib-castv2) worked for me but I can't remember if it also opened YouTube videos.
Moved to casting using a dart package so I am not running it anymore.

**Comment by guyluz11** [comment]
> So, did someone ever figured this out?

[node-red-contrib-castv2](https://flows.nodered.org/node/node-red-contrib-castv2) worked for me but I can't remember if it also opened YouTube videos.
Moved to cast using a dart package so I am not running it anymore.
