### ISSUE TITLE
Group Cast - Device keeps changing

### ISSUE THREAD

**Issue by marc-gist** [Hypnos3/node-red-contrib-cast#91]
Not an issue with your amazing work!  But not sure where else to seek help, or perhaps you have an idea how to "fix" (deal with the issue).

Your amazing nodes send TTS perfectly for me; way more reliable than HomeAssistant.
However; what I have noticed is that with my setup (5 devices), the grup port, typically 42379 keeps moving from device to device.

For example: I have static IPs for all my google devices so that its easy to work with this node:

Mini 1 @ .22
Mini 2 @ .23
etc..

Typically the group port has been open/available on Mini 1 so .23:42379 and sending to it works great.

Then, for no know reason, the group port isn't open on Mini 1 anymore, but now is on say Mini 2, or one of the other devices in my home.  So I have to update the Node to accommodate for that :(

Perhaps you can add a group node, or group option to your code that will try a list of devices to see which one has the open port, say do it every X hours?

Thanks again!

**Comment by adizag** [comment]
How can you chromecast to a group? how can you find the exact port?

**Comment by marc-gist** [comment]
> How can you chromecast to a group? how can you find the exact port?

Mine have always been on 42379 far as I recall. but to scan, i use `nmap`

> \# nmap -p 1-65000 192.168.1.99

where 192.168.1.99 is the IP of the google device.

**Comment by adizag** [comment]
Thanks @marc-gist , just found it with your help!

**Comment by Hypnos3** [comment]
@adizag: If the node is once deployed you can search for cast devices and Groups are also in the list.

@marc-gist: I can implement a search for multiple ports. But this will delays the output significantly. I will try the first port and if I get an error I will try the next one and so on.

**Comment by markusElse** [comment]
Thanks for the great work on the cast topic! Its highly appreciated!!

is there a way to use the discovery function from within a flow to make it update the group IP/port automatically?

Also I see a quite long list of connections from the cast nodes discovery function with some old entries obviously - can this list be cleared before doing a new scan?
