### ISSUE TITLE
How to increase the streaming speed

### ISSUE THREAD

**Issue by pavanmadem** [Hypnos3/node-red-contrib-cast#92]
Hi ,

I am playing a local video file from Rpi . I created an endpioint in node red . The video file size is around 30 MB. It takes 2 min to reach to the endpoint and play the file . Is there a way that we can increase the speed ?

Thanks !

**Comment by Hypnos3** [comment]
I have no idea. The node only sends the url to the cast device. It is up to the google protocol.

**Comment by andreypopov** [comment]
same issue. I stream online radio, it takes 30 seconds to start playing..
